version: 2.1

default_image: &default_image
  executor:
    name: node/default
    tag: "14.15.1"

default_resource_class: &default_resource_class
  resource_class: medium

defaults: &defaults
  <<: *default_image
  <<: *default_resource_class

orbs:
  node: circleci/node@4.7.0
  nx: nrwl/nx@1.0.0

nx-cache: &nx-cache
  key: nx-cloud-recipe-{{ checksum "yarn.lock" }}

# Reusable Commands
commands:
  yarn_install:
    description: Install Packages
    steps:
      - node/install-packages:
          include-branch-in-cache-key: false
          cache-version: v3
          pkg-manager: yarn
      - save_cache:
          <<: *nx-cache
          paths:
            - ~/.cache

  restore_npm_cache:
    description: 'Restore Cached Dependencies'
    steps:
      - restore_cache:
          <<: *nx-cache

  setup:
    description: 'Setup Executor'
    steps:
      - checkout
      - nx/set-shas
      - attach_workspace:
          at: ~/project

# Available Jobs
jobs:
  initialise:
    <<: *defaults
    steps:
      - checkout
      - restore_npm_cache
      - yarn_install
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - dist

  build:
    <<: *defaults
    steps:
      - setup
      - run:
          command: >-
            yarn nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --parallel
            --max-parallel=3
          name: Run Builds
      - store_artifacts:
          path: dist

  lint:
    <<: *defaults
    steps:
      - setup
      - run:
          command: >-
            yarn nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD --parallel --ci
            --max-parallel=2
          name: Run Linting

  test:
    docker:
      - image: tiltdev/circleci-kind:v1.4.0
    steps:
      - setup_remote_docker
      - node/install:
          install-yarn: true
          node-version: 14.15.1
      - setup
      - run:
          command: >-
            with-kind-cluster.sh yarn nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --parallel --ci
            --max-parallel=2
          name: Run Unit Tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build-and-test:
    jobs:
      - initialise
      - build:
          requires:
            - initialise
      - lint:
          requires:
            - initialise
      - test:
          requires:
            - initialise
